
name: C/C++ CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  macos-universal-build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: ["x86", "x64"]
        precision: ["single", "double"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install PureData and Deps
        run: |
          brew install --cask pd
      - name: Build Object
        run: |
          cmake . -B build
          cmake --build build
      - name: Upload Object
        uses: actions/upload-artifact@v3
        with:
          name: perceptron-macos-${{ matrix.arch }}-${{ matrix.precision }}
          path: Binaries
  windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: ["x86", "x64"]
        precision: ["single", "double"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - if: runner.os == 'Windows'
        name: "Install mingw deps"
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          platform: x64
          install: make mingw-w64-x86_64-gcc mingw64/mingw-w64-x86_64-cmake
          update: false
      - name: Install PureData
        run: |
          choco install puredata --yes
      - if: runner.os == 'Windows'
        name: Build Object
        shell: msys2 {0}
        run: |
          cmake . -B build
          cmake --build build
          rm perceptron/*.a
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: perceptron-macos-${{ matrix.arch }}-${{ matrix.precision }}
          path: Binaries
  linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["x86", "x64"]
        precision: ["single", "double"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: PureData Sources
        run: |
          sudo apt-get update
          sudo add-apt-repository ppa:pure-data/pure-data -y
          sudo apt-get install puredata -y
      - name: Build Object
        run: |
          cmake . -B build
          cmake --build build
      - name: Upload Object
        uses: actions/upload-artifact@v3
        with:
          name: perceptron-macos-${{ matrix.arch }}-${{ matrix.precision }}
          path: Binaries
